version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 2600:27017
    environment:
      - MONGO_INITDB_DATABASE=iot
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    restart: always
    networks:
      - mongo-network

networks:
  mongo-network:
    driver: bridge