version: '3'
services:
  mysql-iot:
    container_name: mysql-iot
    image: mysql:8.0.31
    restart: always
    ports:
      - "33006:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: iot
    command: --lower_case_table_names=2
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mysql-network

networks:
  mysql-network:
    driver: bridge
  
# docker exec mysql-iot sh -c 'exec mysqldump -uroot -proot iot > backup.sql' && docker cp mysql-iot/backup.sql ./docker-iot/backup.sql